<a href="https://colab.research.google.com/github/nihaar06/Numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
arr1=np.array([1,2,3])
print(arr1)

[1 2 3]


In [ ]:
arr_2d=np.array([[1,2,3],[4,5,6]])

In [ ]:
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr_3d=np.array([[[1,2,3],[4,5,6]],[[7,9,10],[81,-2,0]]])
print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  9 10]
  [81 -2  0]]]


In [ ]:
print(arr1.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)

1
2
3


In [ ]:
zeros=np.zeros((2,3,4))
print(zeros)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
ones=np.ones((3,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
r=np.random.random((2,2))
print(r)

[[0.12230651 0.33984309]
 [0.59041777 0.74385784]]


In [ ]:
ar=np.arange(0,9,1.5)

In [ ]:
print(ar)

[0.  1.5 3.  4.5 6.  7.5]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print('Size:',arr.size)
print("Shape:",arr.shape)
print("Dimensions:",arr.ndim)
print("Datatype:",arr.dtype)

Size: 6
Shape: (2, 3)
Dimensions: 2
Datatype: int64


You are working as a Data Engineer for a smart agriculture startup that collects sensor data from multiple greenhouses.
Each greenhouse has sensors that record temperature (°C) readings at different times of the day.
You received the following data:
Your tasks are:
Create NumPy arrays
Create a 2D NumPy array named temp_data to represent the temperature readings from both greenhouses.
Print the array.
Check array properties
Print the shape, size, data type, and number of dimensions of temp_data.
Add a third greenhouse
The third greenhouse (GH3) records [21, 23, 22].
Create a new array updated_temp_data that includes all three greenhouses.
Generate supporting data
Create a zeros array (2×3) called sensor_error_flags to represent whether there were any sensor errors (0 means no error).
Create an identity matrix of size 3×3 named greenhouse_identity to uniquely identify each greenhouse.
Display all arrays
Print updated_temp_data, sensor_error_flags, and greenhouse_identity.

In [ ]:
temp_data=np.array([[22,25,20],[24,26,23]])
print(temp_data)
print("Size:",temp_data.size)
print("Shape:",temp_data.shape)
print("Data Type:",temp_data.dtype)
print("Dimensions:",temp_data.ndim)

[[22 25 20]
 [24 26 23]]
Size: 6
Shape: (2, 3)
Data Type: int64
Dimensions: 2


In [ ]:
updated_temp_data=np.append(temp_data,[[21,23,22]],axis=0)
print(updated_temp_data)

[[22 25 20]
 [24 26 23]
 [21 23 22]]


In [ ]:
sensor_error_flags=np.zeros((2,3))
greenhouse_identity=np.eye(3)

In [ ]:
print("Updated GreenHouse Data:\n",updated_temp_data)
print("Sensor Error Flags:\n",sensor_error_flags)
print("GreenHouse Identity:\n",greenhouse_identity)

Updated GreenHouse Data:
 [[22 25 20]
 [24 26 23]
 [21 23 22]]
Sensor Error Flags:
 [[0. 0. 0.]
 [0. 0. 0.]]
GreenHouse Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr=np.array([[1,4,9],[2,0,5]])
print(arr[:,1:3])
print(arr[1,0:2])

[[4 9]
 [0 5]]
[2 0]


Indexing and Slicing:
You are working as a Data Analyst at a fruit distribution company.
The company stores the number of fruit boxes shipped per day (for 1 week) in a 2D NumPy array where:
Each row represents a type of fruit.
Each column represents a day of the week (Mon–Sun).


Your Tasks
Create the 2D NumPy array
Create an array named shipments using the above data.
Access single elements (Indexing):
Get the number of Apples shipped on Wednesday.
Get the number of Oranges shipped on Sunday.
Access multiple elements (Slicing):
Extract all the weekday shipments (Mon–Fri) for all fruits.
Extract only the weekend shipments (Sat & Sun).
Extract the shipments of Apples from Wednesday to Saturday.
Bonus (Practice thinking):
Replace the Saturday shipment of Apples (currently 80) with 100 using indexing.

In [ ]:
shipments=np.array([[50,60,55,70,65,80,90],[40,45,50,60,55,70,75]])
print("Shipments:\n",shipments)

Shipments:
 [[50 60 55 70 65 80 90]
 [40 45 50 60 55 70 75]]


In [ ]:
print("Number of Apples shipped on Wednesday:",shipments[0,2])
print("Number of Oranges shipped on Sunday:",shipments[1,6])

Number of Apples shipped on Wednesday: 55
Number of Oranges shipped on Sunday: 75


In [ ]:
print("Weekday Shipments of all fruits:",shipments[:,0:5])

Weekday Shipments of all fruits: [[50 60 55 70 65]
 [40 45 50 60 55]]


In [ ]:
print("Weekend Shipments of all fruits:",shipments[:,5:7])
print("Shipments of Appples from Wednesday to Saturday:",shipments[0,2:7])

Weekend Shipments of all fruits: [[80 90]
 [70 75]]
Shipments of Appples from Wednesday to Saturday: [55 70 65 80 90]


In [ ]:
shipments[0,5]=100
print(shipments)

[[ 50  60  55  70  65 100  90]
 [ 40  45  50  60  55  70  75]]


In [ ]:
a=np.array([1,2,3])
b=np.array([1,2,8])
print(a+b)

[ 2  4 11]


In [ ]:
print(a*b)

[ 1  4 24]


In [ ]:
a=np.array([[1,2,3],[7,5,6]])
print(np.cross(a,b))

[[ 10  -5   0]
 [ 28 -50   9]]


In [ ]:
print(a+2)

[[3 4 5]
 [9 7 8]]


In [ ]:
arr=np.array([3,6,9])
print("Exponent:",np.exp(arr))

Exponent: [  20.08553692  403.42879349 8103.08392758]


In [ ]:
print("Logarithmic:",np.log(arr))
print("Square Root:",np.sqrt(arr))
print("Exp1:",np.expm1(arr))

Logarithmic: [1.09861229 1.79175947 2.19722458]
Square Root: [1.73205081 2.44948974 3.        ]
Exp1: [  19.08553692  402.42879349 8102.08392758]


In [ ]:
print("Sin:",np.sin(arr))
print("Cos:",np.cos(arr))
print("Tan:",np.tan(arr))

Sin: [ 0.14112001 -0.2794155   0.41211849]
Cos: [-0.9899925   0.96017029 -0.91113026]
Tan: [-0.14254654 -0.29100619 -0.45231566]


In [ ]:
print("Radians:",np.radians(arr))

Radians: [0.05235988 0.10471976 0.15707963]


In [ ]:
print("Degrees:",np.degrees(arr))

Degrees: [171.88733854 343.77467708 515.66201562]


In [ ]:
print(np.trunc(9.999999))

9.0


In [ ]:
np.prod(arr)

np.int64(162)

In [ ]:
np.logical_xor(0,1)

np.True_

In [ ]:
print(np.not_equal(13,15))

True


In [ ]:
np.bitwise_or(2,3)

np.int64(3)

You are a data engineer at a renewable-energy company that runs 3 solar farms.

Each farm has 4 solar panels, and each panel reports hourly energy production (kWh) for 3 hours during a test window.

Given data (raw)
Create arrays from these values:
production — shape (3 farms × 4 panels × 3 hours) represented as a 2D array per farm (you can stack/create as shown in tasks).
Farm A panels (rows = panels, cols = hours):


Tasks
Create arrays
Create three 2D NumPy arrays farmA, farmB, farmC (each shape (4,3)).
Stack them into a single 3D array production_all of shape (3, 4, 3).
Array attributes
Print the .shape, .size, .dtype, and .ndim of production_all.
Per-farm totals (arithmetic & aggregation)
Use aggregation ufuncs to compute the total energy per farm (sum across panels & hours) → total_per_farm (shape (3,)).
Compute mean, std, and var per farm.
Per-hour matrix multiplication idea (matrix op)
For a quick weighted estimate, create a hour_weights row vector of shape (3,) = [0.5, 1.0, 0.75] (weights for hour1, hour2, hour3).
Compute weighted_per_panel by performing a dot product between each farm's panel-row and hour_weights to get per-panel weighted energy. (Use np.dot / matrix multiplication appropriately.)
Broadcasting adjustments
The operator notices a fixed calibration offset of +0.5 kWh for all panels in Farm B. Use broadcasting to add this offset to Farm B data inside production_all (without recreating whole array manually).
Element-wise arithmetic (ufuncs: add/sub/mul/div/power/mod)
Compute a normalized version where you:
subtract the per-farm mean (use broadcasting),
divide by the per-farm std (broadcasting) — i.e., z-score normalize each farm's panel-hour readings.
Apply many ufuncs (use the ufuncs listed previously)

Apply the following element-wise operations (create variables for each) on the normalized data (or a copy) and show the resulting arrays (or summaries — shape/dtype/first row) where appropriate:
Exponential family: np.exp, np.expm1, np.log (note: handle non-positive inputs if needed), np.log10, np.log2.
Trigonometric: np.sin, np.cos, np.tan, np.arcsin, np.arccos, np.arctan, plus np.degrees, np.radians applied appropriately.
Rounding: np.round, np.floor, np.ceil, np.trunc.
Comparison & logical ufuncs: create a boolean mask high_output = production_all > 20 and apply np.logical_and, np.logical_or, np.logical_not, np.logical_xor combining masks (e.g., high_output and even_hours_mask). Also use comparison ufuncs like np.greater_equal, np.less.
Bitwise ufuncs (on integer arrays): create an integer array alerts = np.array([[1,0,1],[0,0,1],[1,1,0],[0,1,0]]) for each farm (shape match required) — then apply np.bitwise_and, np.bitwise_or, np.invert where sensible.
Arithmetic ufuncs again: np.add, np.subtract, np.multiply, np.divide, np.power, np.mod.
Aggregations over ufunc outputs: e.g., np.sum(np.exp(...)), np.mean(np.sin(...)).
Broadcast-based summary table
Use broadcasting to compute a (3,4) array panel_totals_per_farm = total per panel (sum across hours for each panel), and then compute a (3,) boolean needs_maintenance saying True if any panel in that farm has total < 40. Use np.min, np.max, np.any, np.all.
Final KPIs (aggregation)
Compute:
overall_total (sum of all farms),
peak_hour value (max across hours) and which farm & panel produced it (use np.argmax with careful unraveling),
average_per_panel across all farms.



In [ ]:
production=np.empty((3,4,3))
production.shape

(3, 4, 3)

In [ ]:
print("Prodcution:\n",production)

Prodcution:
 [[[10 12 11]
  [ 9 11 10]
  [12 13 14]
  [ 8  7  9]]

 [[20 19 21]
  [18 20 19]
  [22 23 21]
  [17 18 16]]

 [[15 16 14]
  [14 13 15]
  [16 17 18]
  [12 11 13]]]


In [ ]:
farmA=np.array([[10,12,11],[9,11,10],[12,13,14],[8,7,9]])
farmB=np.array([[20,19,21],[18,20,19],[22,23,21],[17,18,16]])
farmC=np.array([[15,16,14],[14,13,15],[16,17,18],[12,11,13]])
farmA.shape

(4, 3)

In [ ]:
production_all=np.empty((3,4,3))
production_all=np.stack((farmA,farmB,farmC),axis=0)
print(production_all)

[[[10 12 11]
  [ 9 11 10]
  [12 13 14]
  [ 8  7  9]]

 [[20 19 21]
  [18 20 19]
  [22 23 21]
  [17 18 16]]

 [[15 16 14]
  [14 13 15]
  [16 17 18]
  [12 11 13]]]


In [ ]:
print('Shape:',production_all.shape)
print('Size:',production_all.size)
print('Data Type:',production_all.dtype)
print('Dimensions:',production_all.ndim)

Shape: (3, 4, 3)
Size: 36
Data Type: int64
Dimensions: 3


In [ ]:
total_per_farm=np.sum(production_all,axis=(1,2))
print("Sum:",total_per_farm)
print("Mean:",np.mean(production_all,axis=(1,2)))
print("Variance:",np.var(production_all,axis=(1,2)))
print("Standard Deviation:",np.std(production_all,axis=(1,2)))

Sum: [126 234 174]
Mean: [10.5 19.5 14.5]
Variance: [3.91666667 3.91666667 3.91666667]
Standard Deviation: [1.97905701 1.97905701 1.97905701]


In [ ]:
hour_weights=np.array([0.5,1.0,0.75])
weighted_per_panel=np.dot(production_all,hour_weights)
print("Weighted per panel:\n",weighted_per_panel)


Weighted per panel:
 [[25.25 23.   29.5  17.75]
 [44.75 43.25 49.75 38.5 ]
 [34.   31.25 38.5  26.75]]


In [ ]:
production_all=production_all.astype('float64')
production_all[1,:,:]+=0.5
print(production_all)

[[[10.  12.  11. ]
  [ 9.  11.  10. ]
  [12.  13.  14. ]
  [ 8.   7.   9. ]]

 [[20.5 19.5 21.5]
  [18.5 20.5 19.5]
  [22.5 23.5 21.5]
  [17.5 18.5 16.5]]

 [[15.  16.  14. ]
  [14.  13.  15. ]
  [16.  17.  18. ]
  [12.  11.  13. ]]]


In [ ]:
normalized=production_all-np.mean(production_all,axis=(1,2))
print(normalized)

[[[ -0.5  -8.   -3.5]
  [ -1.5  -9.   -4.5]
  [  1.5  -7.   -0.5]
  [ -2.5 -13.   -5.5]]

 [[ 10.   -0.5   7. ]
  [  8.    0.5   5. ]
  [ 12.    3.5   7. ]
  [  7.   -1.5   2. ]]

 [[  4.5  -4.   -0.5]
  [  3.5  -7.    0.5]
  [  5.5  -3.    3.5]
  [  1.5  -9.   -1.5]]]


In [ ]:
std=np.std(production_all,axis=(1,2))
normalized=normalized/std
print(normalized)

[[[-0.25264558 -4.04232922 -1.76851903]
  [-0.75793673 -4.54762037 -2.27381019]
  [ 0.75793673 -3.53703807 -0.25264558]
  [-1.26322788 -6.56878498 -2.77910134]]

 [[ 5.05291153 -0.25264558  3.53703807]
  [ 4.04232922  0.25264558  2.52645576]
  [ 6.06349383  1.76851903  3.53703807]
  [ 3.53703807 -0.75793673  1.01058231]]

 [[ 2.27381019 -2.02116461 -0.25264558]
  [ 1.76851903 -3.53703807  0.25264558]
  [ 2.77910134 -1.51587346  1.76851903]
  [ 0.75793673 -4.54762037 -0.75793673]]]


In [ ]:
print("Exp:\n",np.exp(normalized))
print("Empm1:\n",np.expm1(normalized))
print("Log:\n",np.log(normalized))
print("Log base 10:\n",np.log10(normalized))
print("Log base 2:\n",np.log2(normalized))

Exp:
 [[[7.76743129e-01 1.75565317e-02 1.70585433e-01]
  [4.68632346e-01 1.05923803e-02 1.02919290e-01]
  [2.13386893e+00 2.90993900e-02 7.76743129e-01]
  [2.82739901e-01 1.40350165e-03 6.20942840e-02]]

 [[1.56477390e+02 7.76743129e-01 3.43649816e+01]
  [5.69588582e+01 1.28742690e+00 1.25090923e+01]
  [4.29874726e+02 5.86216526e+00 3.43649816e+01]
  [3.43649816e+01 4.68632346e-01 2.74720026e+00]]

 [[9.71635149e+00 1.32501063e-01 7.76743129e-01]
  [5.86216526e+00 2.90993900e-02 1.28742690e+00]
  [1.61045419e+01 2.19616275e-01 5.86216526e+00]
  [2.13386893e+00 1.05923803e-02 4.68632346e-01]]]
Empm1:
 [[[-2.23256871e-01 -9.82443468e-01 -8.29414567e-01]
  [-5.31367654e-01 -9.89407620e-01 -8.97080710e-01]
  [ 1.13386893e+00 -9.70900610e-01 -2.23256871e-01]
  [-7.17260099e-01 -9.98596498e-01 -9.37905716e-01]]

 [[ 1.55477390e+02 -2.23256871e-01  3.33649816e+01]
  [ 5.59588582e+01  2.87426901e-01  1.15090923e+01]
  [ 4.28874726e+02  4.86216526e+00  3.33649816e+01]
  [ 3.33649816e+01 -5.3136

/tmp/ipython-input-2089459705.py:3: RuntimeWarning: invalid value encountered in log
  print("Log:\n",np.log(normalized))
/tmp/ipython-input-2089459705.py:4: RuntimeWarning: invalid value encountered in log10
  print("Log base 10:\n",np.log10(normalized))
/tmp/ipython-input-2089459705.py:5: RuntimeWarning: invalid value encountered in log2
  print("Log base 2:\n",np.log2(normalized))


In [ ]:
print("Trignometric Functions\n")
print("Sin:",np.sin(normalized))
print("Cos:",np.cos(normalized))
print("Tan:",np.tan(normalized))
print("arcsin:",np.arcsin(normalized))
print("arccos:",np.arccos(normalized))
print("arctan:",np.arctan(normalized))
print("degrees:",np.degrees(normalized))
print("Radians:",np.radians(normalized))

Trignometric Functions

Sin: [[[-0.24996642  0.78378455 -0.98051646]
  [-0.68742445  0.98645634 -0.76289713]
  [ 0.68742445  0.38521927 -0.24996642]
  [-0.95307252 -0.28173289 -0.35460475]]

 [[-0.94258027 -0.24996642 -0.38521927]
  [-0.78378455  0.24996642  0.57707033]
  [-0.21792852  0.98051646 -0.38521927]
  [-0.38521927 -0.68742445  0.84714141]]

 [[ 0.76289713 -0.90028685 -0.24996642]
  [ 0.98051646  0.38521927  0.24996642]
  [ 0.35460475 -0.99849212  0.98051646]
  [ 0.68742445  0.98645634 -0.68742445]]]
Cos: [[[ 0.96825451 -0.62103283 -0.19643692]
  [ 0.7262559  -0.16402408 -0.64651989]
  [ 0.7262559  -0.92282507  0.96825451]
  [ 0.30274209  0.95949288 -0.93501629]]

 [[ 0.33397968  0.96825451 -0.92282507]
  [-0.62103283  0.96825451 -0.81669446]
  [ 0.97596473 -0.19643692 -0.92282507]
  [-0.92282507  0.7262559   0.53136752]]

 [[-0.64651989 -0.43529712  0.96825451]
  [-0.19643692 -0.92282507  0.96825451]
  [-0.93501629  0.05489526 -0.19643692]
  [ 0.7262559  -0.16402408  0.726255

/tmp/ipython-input-1878536153.py:5: RuntimeWarning: invalid value encountered in arcsin
  print("arcsin:",np.arcsin(normalized))
/tmp/ipython-input-1878536153.py:6: RuntimeWarning: invalid value encountered in arccos
  print("arccos:",np.arccos(normalized))


In [ ]:
print("Rounding Functions\n")
print("Round:", np.round(normalized))
print("Floor:", np.floor(normalized))
print("Ceil:", np.ceil(normalized))
print("Trunc:", np.trunc(normalized))

Rounding Functions

Round: [[[-0. -4. -2.]
  [-1. -5. -2.]
  [ 1. -4. -0.]
  [-1. -7. -3.]]

 [[ 5. -0.  4.]
  [ 4.  0.  3.]
  [ 6.  2.  4.]
  [ 4. -1.  1.]]

 [[ 2. -2. -0.]
  [ 2. -4.  0.]
  [ 3. -2.  2.]
  [ 1. -5. -1.]]]
Floor: [[[-1. -5. -2.]
  [-1. -5. -3.]
  [ 0. -4. -1.]
  [-2. -7. -3.]]

 [[ 5. -1.  3.]
  [ 4.  0.  2.]
  [ 6.  1.  3.]
  [ 3. -1.  1.]]

 [[ 2. -3. -1.]
  [ 1. -4.  0.]
  [ 2. -2.  1.]
  [ 0. -5. -1.]]]
Ceil: [[[-0. -4. -1.]
  [-0. -4. -2.]
  [ 1. -3. -0.]
  [-1. -6. -2.]]

 [[ 6. -0.  4.]
  [ 5.  1.  3.]
  [ 7.  2.  4.]
  [ 4. -0.  2.]]

 [[ 3. -2. -0.]
  [ 2. -3.  1.]
  [ 3. -1.  2.]
  [ 1. -4. -0.]]]
Trunc: [[[-0. -4. -1.]
  [-0. -4. -2.]
  [ 0. -3. -0.]
  [-1. -6. -2.]]

 [[ 5. -0.  3.]
  [ 4.  0.  2.]
  [ 6.  1.  3.]
  [ 3. -0.  1.]]

 [[ 2. -2. -0.]
  [ 1. -3.  0.]
  [ 2. -1.  1.]
  [ 0. -4. -0.]]]


In [ ]:
print("Comparison & Logical Ufuncs\n")
high_output = production_all > 20
print("high_output:\n", high_output)
print("Greater Equal (production_all >= 20):\n", np.greater_equal(production_all, 20))
print("Less (production_all < 15):\n", np.less(production_all, 15))

Comparison & Logical Ufuncs

high_output:
 [[[False False False]
  [False False False]
  [False False False]
  [False False False]]

 [[ True False  True]
  [False  True False]
  [ True  True  True]
  [False False False]]

 [[False False False]
  [False False False]
  [False False False]
  [False False False]]]
Greater Equal (production_all >= 20):
 [[[False False False]
  [False False False]
  [False False False]
  [False False False]]

 [[ True False  True]
  [False  True False]
  [ True  True  True]
  [False False False]]

 [[False False False]
  [False False False]
  [False False False]
  [False False False]]]
Less (production_all < 15):
 [[[ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[False False False]
  [False False False]
  [False False False]
  [False False False]]

 [[False False  True]
  [ True  True False]
  [False False False]
  [ True  True  True]]]


In [ ]:
print("Bitwise Ufuncs\n")
alerts = np.array([[[1,0,1],[0,0,1],[1,1,0],[0,1,0]],
                   [[1,0,1],[0,0,1],[1,1,0],[0,1,0]],
                   [[1,0,1],[0,0,1],[1,1,0],[0,1,0]]])
print("Alerts:\n", alerts)
print("Bitwise AND (production_all > 15 & alerts):\n", np.bitwise_and((production_all > 15).astype(int), alerts))
print("Bitwise OR (production_all > 15 | alerts):\n", np.bitwise_or((production_all > 15).astype(int), alerts))
print("Bitwise INVERT (~alerts):\n", np.invert(alerts))

Bitwise Ufuncs

Alerts:
 [[[1 0 1]
  [0 0 1]
  [1 1 0]
  [0 1 0]]

 [[1 0 1]
  [0 0 1]
  [1 1 0]
  [0 1 0]]

 [[1 0 1]
  [0 0 1]
  [1 1 0]
  [0 1 0]]]
Bitwise AND (production_all > 15 & alerts):
 [[[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[1 0 1]
  [0 0 1]
  [1 1 0]
  [0 1 0]]

 [[0 0 0]
  [0 0 0]
  [1 1 0]
  [0 0 0]]]
Bitwise OR (production_all > 15 | alerts):
 [[[1 0 1]
  [0 0 1]
  [1 1 0]
  [0 1 0]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [0 0 1]
  [1 1 1]
  [0 1 0]]]
Bitwise INVERT (~alerts):
 [[[-2 -1 -2]
  [-1 -1 -2]
  [-2 -2 -1]
  [-1 -2 -1]]

 [[-2 -1 -2]
  [-1 -1 -2]
  [-2 -2 -1]
  [-1 -2 -1]]

 [[-2 -1 -2]
  [-1 -1 -2]
  [-2 -2 -1]
  [-1 -2 -1]]]


In [ ]:
print("Arithmetic Ufuncs\n")
print("Add (production_all + 5):\n", np.add(production_all, 5))
print("Subtract (production_all - 2):\n", np.subtract(production_all, 2))
print("Multiply (production_all * 1.1):\n", np.multiply(production_all, 1.1))
print("Divide (production_all / 2):\n", np.divide(production_all, 2))
print("Power (production_all ** 2):\n", np.power(production_all, 2))
print("Mod (production_all % 3):\n", np.mod(production_all, 3))

Arithmetic Ufuncs

Add (production_all + 5):
 [[[15.  17.  16. ]
  [14.  16.  15. ]
  [17.  18.  19. ]
  [13.  12.  14. ]]

 [[25.5 24.5 26.5]
  [23.5 25.5 24.5]
  [27.5 28.5 26.5]
  [22.5 23.5 21.5]]

 [[20.  21.  19. ]
  [19.  18.  20. ]
  [21.  22.  23. ]
  [17.  16.  18. ]]]
Subtract (production_all - 2):
 [[[ 8.  10.   9. ]
  [ 7.   9.   8. ]
  [10.  11.  12. ]
  [ 6.   5.   7. ]]

 [[18.5 17.5 19.5]
  [16.5 18.5 17.5]
  [20.5 21.5 19.5]
  [15.5 16.5 14.5]]

 [[13.  14.  12. ]
  [12.  11.  13. ]
  [14.  15.  16. ]
  [10.   9.  11. ]]]
Multiply (production_all * 1.1):
 [[[11.   13.2  12.1 ]
  [ 9.9  12.1  11.  ]
  [13.2  14.3  15.4 ]
  [ 8.8   7.7   9.9 ]]

 [[22.55 21.45 23.65]
  [20.35 22.55 21.45]
  [24.75 25.85 23.65]
  [19.25 20.35 18.15]]

 [[16.5  17.6  15.4 ]
  [15.4  14.3  16.5 ]
  [17.6  18.7  19.8 ]
  [13.2  12.1  14.3 ]]]
Divide (production_all / 2):
 [[[ 5.    6.    5.5 ]
  [ 4.5   5.5   5.  ]
  [ 6.    6.5   7.  ]
  [ 4.    3.5   4.5 ]]

 [[10.25  9.75 10.75]
  [ 9.25

In [ ]:
print("Broadcast-based Summary Table\n")
panel_totals_per_farm = np.sum(production_all, axis=2)
print("Panel Totals Per Farm:\n", panel_totals_per_farm)

needs_maintenance = np.any(panel_totals_per_farm < 40, axis=1)
print("Needs Maintenance:\n", needs_maintenance)

print("Minimum per farm:\n", np.min(production_all, axis=(1,2)))
print("Maximum per farm:\n", np.max(production_all, axis=(1,2)))
print("Any production above 25 per farm:\n", np.any(production_all > 25, axis=(1,2)))
print("All production above 5 per farm:\n", np.all(production_all > 5, axis=(1,2)))

Broadcast-based Summary Table

Panel Totals Per Farm:
 [[33.  30.  39.  24. ]
 [61.5 58.5 67.5 52.5]
 [45.  42.  51.  36. ]]
Needs Maintenance:
 [ True False  True]
Minimum per farm:
 [ 7.  16.5 11. ]
Maximum per farm:
 [14.  23.5 18. ]
Any production above 25 per farm:
 [False False False]
All production above 5 per farm:
 [ True  True  True]


In [ ]:
print("Final KPIs\n")
overall_total = np.sum(production_all)
print("Overall Total Production:", overall_total)

peak_hour_value = np.max(production_all)
print("Peak Hour Value:", peak_hour_value)

peak_hour_location = np.argmax(production_all)
farm, panel, hour = np.unravel_index(peak_hour_location, production_all.shape)
print(f"Peak Hour Location (Farm, Panel, Hour): ({farm}, {panel}, {hour})")

average_per_panel = np.mean(production_all, axis=(0, 2))
print("Average Production Per Panel (across all farms):", average_per_panel)

Final KPIs

Overall Total Production: 540.0
Peak Hour Value: 23.5
Peak Hour Location (Farm, Panel, Hour): (1, 2, 1)
Average Production Per Panel (across all farms): [15.5 14.5 17.5 12.5]


In [ ]:
arr=np.array([1,2,3,4,5,6])
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a=np.array([1,2])
b=np.array([3,4])
print(np.vstack((a,b)))
print(np.hstack((a,b)))
arr=np.array([1,2,3,4,5,6])
print(np.array_split(arr,3))

[[1 2]
 [3 4]]
[1 2 3 4]
[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
arr=np.array([1,2,3,4,5,6])
print(arr[arr>3])

[4 5 6]


In [ ]:
ind=[4,0,2]
print(arr[ind])

[5 1 3]


In [ ]:
#View shares memory
view=arr.view()
view[0]=69
print("View:",view)
print("Array:",arr)

View: [69  2  3  4  5  6]
Array: [69  2  3  4  5  6]
None


In [ ]:
#Copy shares memory
copy=arr.copy()
copy[0]=89
print("Copy:",copy)
print("Array:",arr)

Copy: [89  2  3  4  5  6]
Array: [69  2  3  4  5  6]


In [ ]:
np.save('array.npy',arr)


In [ ]:
a=np.load('array.npy')
print(a)

[69  2  3  4  5  6]


TasksArray Creation
Create a 1D array of numbers from 10 to 50.
Create a 3x3 array of random numbers between 0 and 1.
Array Attributes
Find the shape, size, and data type of the array you created in the previous task.
Basic Operations
Add 5 to every element of a 1D array.
Multiply two 2D arrays element-wise.
Indexing and Slicing
Create a 5x5 array of integers from 1 to 25. Extract:
The first row.
The last column.
A subarray of the first three rows and first two columns.
Aggregation
Create a 10-element array of random integers between 10 and 100. Find:
The maximum value.
The minimum value.
The mean and standard deviation.
Reshaping
Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
Broadcasting
Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
Filtering
Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
Matrix Multiplication
Create two 2x2 matrices and perform matrix multiplication.
Advanced Indexing
Given a 4x4 array, use fancy indexing to extract the diagonal elements.

In [ ]:
TasksArray=np.arange(10,51)
print(TasksArray)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
r=np.random.random((3,3))
print(r)

[[0.51331517 0.3720607  0.4421892 ]
 [0.42405727 0.44680378 0.49155933]
 [0.44819578 0.88236851 0.47493116]]


In [ ]:
print("Shape:",r.shape)
print("Size:",r.size)
print("Datatype:",r.dtype)

Shape: (3, 3)
Size: 9
Datatype: float64


In [ ]:
TasksArray+=5
print("TasksArray after adding 5:",TasksArray)

TasksArray after adding 5: [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60]


In [ ]:
arr1_2d=np.array([[1,2,3],[7,4,0]])
arr2_2d=np.array([[4,6,2],[2,12,5]])
prod=np.multiply(arr1_2d,arr2_2d)
print(prod)

[[ 4 12  6]
 [14 48  0]]


In [ ]:
arr=np.arange(1,26).reshape(5,5)
print("5x5 Matrix:\n",arr)
print("First row:",arr[0,:])
print("Last column:",arr[:,4])
print("Subarray:\n",arr[0:3,0:2])

5x5 Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
First row: [1 2 3 4 5]
Last column: [ 5 10 15 20 25]
Subarray:
 [[ 1  2]
 [ 6  7]
 [11 12]]


In [ ]:
arr=np.random.randint(10,100,(1,10))
print(arr)
print("Max:",np.max(arr))
print("Min:",np.min(arr))
print("Mean:",np.mean(arr),'Std:',np.std(arr))

[[57 23 30 36 44 43 54 95 53 94]]
Max: 95
Min: 23
Mean: 52.9 Std: 23.15361742795281


In [ ]:
arr=np.arange(1,13)
print("Before reshaping:",arr)
print("After reshaping:\n",arr.reshape(3,4))

Before reshaping: [ 1  2  3  4  5  6  7  8  9 10 11 12]
After reshaping:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
arr=np.ones((3,3))
ad=np.array([1,2,3])
print("Sum:\n",np.add(arr,ad))

Sum:
 [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [ ]:
arr=np.random.randint(1,51,(1,50))
print("Array of random integers from 1 to 50:\n",arr)
print("Elements divisible by 5:\n",arr[arr%5==0])

Array of random integers from 1 to 50:
 [[37  8  8  2 45 47 28 12 16  2 37 10 43 31 28 17 20  9 22 31 21 32 25  6
   9 42 14  6 18 15  5 38 43 15 32 24 10 47  7 30 20  4 15 29 23  2 24 17
   5 12]]
Elements divisible by 5:
 [45 10 20 25 15  5 15 10 30 20 15  5]


In [ ]:
arr1=np.array([[1,2,3],[5,6,7]])
arr2=np.array([[53,24,9],[9,1,4]])
print("Array1:\n",arr1,'\nArray2:\n',arr2)
print("Matrix multiplication:\n",np.cross(arr1,arr2))

Array1:
 [[1 2 3]
 [5 6 7]] 
Array2:
 [[53 24  9]
 [ 9  1  4]]
Matrix multiplication:
 [[-54 150 -82]
 [ 17  43 -49]]


In [ ]:
arr=np.arange(1,17).reshape(4,4)
print("Array:\n",arr)
print("Diagonal elements:",arr[[0,1,2,3],[0,1,2,3]])

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Diagonal elements: [ 1  6 11 16]
